name: Lint PR Files

on:
  pull_request:

jobs:
  run_pre_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Install project deps
      run: |
        pip install -e .
        pip install pre-commit
        pre-commit install
      shell: bash

    - name: Run Tests
      run: |
        echo "$(pwd)"
        sudo chown -R $USER:$USER "$(pwd)"
        if [[ ${{ github.event_name == 'pull_request' }} ]]
        then
          files_changed=`git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }}`;
          echo "$files_changed"
        else
          files_changed=`git merge-base origin/${{ github.event.repository.default_branch }} HEAD`;
          echo "$files_changed"
        fi
        
        files_changed=`$files_changed | xargs || echo ''`

        echo "files_changed: $files_changed"
        echo $files_changed | xargs python3 -m pre_commit run --color=always --files;
      shell: bash