name: Lint PR Files

on:
  pull_request:

jobs:
  run_pre_commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Install project deps
      run: |
        pip install -e .
        pip install pre-commit
        pre-commit install

    - name: Run Tests
      run: |
        files_changed=`$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} | xargs || echo "")`;
        echo "files_changed: $files_changed"
        echo $files_changed | xargs python3 -m pre_commit run --color=always --files;
