name: Run Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  run_tests:
    strategy:
      matrix:
        version: ['3.10', '3.10', '3.12', '3.13']
    uses: .github/workflows/test-base.yml
    with:
      python-version: ${{ matrix.version }}