name: Run Tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: python:${{ inputs.python-version }}-slim-bullseye
    services:
      postgres:
        image: postgres
        ports:
        - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
    - uses: actions/checkout@v4

    - name: Install project deps
      run: pip install -e .[test]

    - name: Run Tests
      run: python -m pytest -rA tests
      env:
        PSQL_ADDRESS: postgres
