name: Run Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim-bullseye
    services:
      postgres:
        image: postgres
        ports:
        - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v4

    - name: Install project deps
      run: pip install -e .[test]

    - name: Run Tests
      run: python -m pytest -rA tests
      env:
        PSQL_ADDRESS: postgres
